---
become_override: False
ocp_username: opentlc-mgr
silent: False

crw_workspace: che
guides_workspace: guides
che_stack_definition: docker.io/schtool/che-quarkus-workshop:latest
num_users: 5
workshop_openshift_user_name: userNN
workshop_openshift_user_password: 'r3dh4t1!'
workshop_che_user_name: userNN
workshop_che_user_password: passNN

workshop_shortenYn: N
workshop_labs_url: "_workshop.yml"

# htaccess configuration 
htpasswd_provider_name: quarkus-lab
htpasswd_file_name: quarkus-htpasswd
htpasswd_secert_name: quarkus-secert

# OCP Limit Range
pod_min_mem: 10Mi
pod_max_mem: 6Gi
container_max_mem: 10Gi
default_min_mem: 256Mi
default_max_mem: 10Gi
default_min_cpu: 500m
default_max_cpu: 1500m


openshift_login: true
openshift_token: XXXXXX
openshift_url: api.ocp4.example.com
insecure_skip_tls_verify: true

#use aws load balancer fix
fix_load_balancer: false

_amqstreams_csv_verison: amqstreams.v1.3.0

# Nexus defaults
nexus_volume_capacity: 100Gi
nexus_max_memory: 8Gi
nexus_min_memory: 4Gi
nexus_max_cpu: 4
nexus_min_cpu: 2

nexus_service_name: nexus

nexus_image_version: 3.12.1

nexus_project_name: nexus
nexus_project_display_name: Nexus
nexus_project_desc: Nexus Repository Manager
# project_annotations:

current_nexus_admin_password: admin123
nexus_admin_user: admin
nexus_admin_password: admin123
openshift_cli: oc
project_admin: admin
